apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: code-pipeline # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "Weaviate Vector Engine"
    scenarios.ai.sap.com/name: "Weaviate"
    executables.ai.sap.com/description: "Weaviate Vector Engine"
    executables.ai.sap.com/name: "Weaviate"
  labels:
    scenarios.ai.sap.com/id: "Weaviate"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: deloitte # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1

  - name: mycodeblock1
    container:
      image: semitechnologies/weaviate:latest
